"""Metadata Generator (Module 11) -- YouTube title/description/tags + polls (Block K)."""
from __future__ import annotations

import re

from modules.schemas import Episode

DISCLAIMER = (
    "This is an educational debate. The arguments are generated by AI language models "
    "assigned to sides by random draw and do NOT represent the views of the creator, the "
    "model providers, or any government."
)
AI_DISCLOSURE = "Voices and arguments in this video are AI-generated."
TITLE_TEMPLATE = "{conflict_phrase} | Two AIs Debate, You Judge"

CHAPTERS = [
    ("0:00", "Hook"), ("0:20", "Introduction"), ("3:00", "Side Assignment"),
    ("3:20", "Round 1: Opening Statements"), ("8:00", "Round 2: Quickfire"),
    ("12:00", "Round 3: Cross-Examination"), ("17:00", "Round 4: Closing Arguments"),
    ("20:00", "Host Verdict"), ("22:00", "Jury Verdict"),
]


def conflict_phrase(thesis: str, max_len: int = 40) -> str:
    """Derive a short conflict phrase from the thesis (<= max_len chars)."""
    phrase = re.sub(r"^(the|a|an)\s+", "", thesis.strip().rstrip("."), flags=re.IGNORECASE)
    phrase = phrase[0].upper() + phrase[1:] if phrase else thesis
    if len(phrase) <= max_len:
        return phrase
    words, out = phrase.split(), ""
    for w in words:
        if len(out) + len(w) + 1 > max_len:
            break
        out = f"{out} {w}".strip()
    return out + "..."


def generate_metadata(
    episode: Episode, prosecution_name: str, defense_name: str
) -> dict:
    phrase = conflict_phrase(episode.thesis)
    title = TITLE_TEMPLATE.format(conflict_phrase=phrase)[:60]
    timestamps = "\n".join(f"{tc} - {label}" for tc, label in CHAPTERS)
    tags = ["NarrativeCourt", "AIDebate", "AI", "Debate"]
    description = f"""Two AI models argue opposite sides. You're the jury.

Today's motion: "{episode.thesis}"

Prosecution ({prosecution_name}): argues the motion stands
Defense ({defense_name}): argues the motion fails

Timestamps:
{timestamps}

Vote BEFORE watching -> pinned Community post

---
DISCLAIMER: {DISCLAIMER}
{AI_DISCLOSURE}

#NarrativeCourt #AIDebate
"""
    return {
        "title": title,
        "description": description,
        "tags": tags,
        "chapters": CHAPTERS,
        "pre_poll": f'Before watching: do you AGREE or DISAGREE that "{episode.thesis}"?',
        "post_poll": f'After watching: AGREE or DISAGREE that "{episode.thesis}"?',
    }
