"""Metadata Generator (Module 11) -- YouTube title/description/tags + polls (Block K)."""
from __future__ import annotations

import re

from modules.schemas import Episode
from modules.timeline.timecode_calculator import _round_sort_key

DISCLAIMER = (
    "This is an educational debate. The arguments are generated by AI language models "
    "assigned to sides by random draw and do NOT represent the views of the creator, the "
    "model providers, or any government."
)
AI_DISCLOSURE = "Voices and arguments in this video are AI-generated."
TITLE_TEMPLATE = "{conflict_phrase} | Two AIs Debate, You Judge"

# Static fallback layout (approximate) used only before a timeline exists.
CHAPTERS = [
    ("0:00", "Hook"), ("0:20", "Introduction"), ("3:00", "Side Assignment"),
    ("3:20", "Round 1: Opening Statements"), ("8:00", "Round 2: Quickfire"),
    ("12:00", "Round 3: Cross-Examination"), ("17:00", "Round 4: Closing Arguments"),
    ("20:00", "Host Verdict"), ("22:00", "Jury Verdict"),
]

_ROUND_LABELS = {
    1: "Round 1: Opening Statements",
    2: "Round 2: Quickfire",
    3: "Round 3: Cross-Examination",
    4: "Round 4: Closing Arguments",
}


def _yt_timestamp(frames: int, fps: int) -> str:
    """Frames -> YouTube chapter stamp ('M:SS' or 'H:MM:SS')."""
    total = int(frames // fps) if fps else 0
    h, rem = divmod(total, 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


def build_chapters(episode: Episode) -> list[tuple[str, str]]:
    """Real chapters from the actual timeline (H2), debate-audio-relative.

    The on-camera human intro/verdict are filmed separately, so these stamps cover
    the generated debate block (Round 1 at 0:00); the host shifts them by the intro
    length in the editor. Falls back to the static layout before a timeline exists.
    """
    td = getattr(episode, "timeline_data", None)
    if not td or not td.clips:
        return list(CHAPTERS)
    starts: dict[int, int] = {}
    for clip in td.clips:
        rnum = _round_sort_key(clip.clip_id)[0]
        if rnum in _ROUND_LABELS:
            starts[rnum] = min(starts.get(rnum, clip.start_frames), clip.start_frames)
    if not starts:
        return list(CHAPTERS)
    chapters: list[tuple[str, str]] = []
    for i, rnum in enumerate(sorted(starts)):
        ts = "0:00" if i == 0 else _yt_timestamp(starts[rnum], td.fps)
        chapters.append((ts, _ROUND_LABELS[rnum]))
    return chapters


def conflict_phrase(thesis: str, max_len: int = 40) -> str:
    """Derive a short conflict phrase from the thesis (<= max_len chars)."""
    phrase = re.sub(r"^(the|a|an)\s+", "", thesis.strip().rstrip("."), flags=re.IGNORECASE)
    phrase = phrase[0].upper() + phrase[1:] if phrase else thesis
    if len(phrase) <= max_len:
        return phrase
    words, out = phrase.split(), ""
    for w in words:
        if len(out) + len(w) + 1 > max_len:
            break
        out = f"{out} {w}".strip()
    return out + "..."


def generate_metadata(
    episode: Episode, prosecution_name: str, defense_name: str
) -> dict:
    phrase = conflict_phrase(episode.thesis)
    title = TITLE_TEMPLATE.format(conflict_phrase=phrase)[:60]
    chapters = build_chapters(episode)  # H2: real timeline-derived chapters
    timestamps = "\n".join(f"{tc} - {label}" for tc, label in chapters)
    tags = ["NarrativeCourt", "AIDebate", "AI", "Debate"]
    description = f"""Two AI models argue opposite sides. You're the jury.

Today's motion: "{episode.thesis}"

Prosecution ({prosecution_name}): argues the motion stands
Defense ({defense_name}): argues the motion fails

Timestamps:
{timestamps}

Vote BEFORE watching -> pinned Community post

---
DISCLAIMER: {DISCLAIMER}
{AI_DISCLOSURE}

#NarrativeCourt #AIDebate
"""
    return {
        "title": title,
        "description": description,
        "tags": tags,
        "chapters": chapters,
        "pre_poll": f'Before watching: do you AGREE or DISAGREE that "{episode.thesis}"?',
        "post_poll": f'After watching: AGREE or DISAGREE that "{episode.thesis}"?',
    }
